version: '3.7'
services:
    # node-cron:
    #     container_name: musicEngine-cron
    #     build: ./cron
    #     command: bash -c "npm install && npm run serve"
    #     ports:
    #         - 3001:3001
    #     networks:
    #         default:
    #             ipv4_address: 192.168.1.82
    #     volumes:
    #         - ./cron:/app
    #         - /app/node_modules

    node-server:
        container_name: musicEngine-server
        build: ./server
        ports:
            - 9000:9000
        # networks:
        #     default:
        #         ipv4_address: 192.168.1.84
        restart: on-failure

    vue-client:
        container_name: musicEngine-client
        build: ./client
        ports:
            - 3000:8080
        # networks:
        #     default:
        #         ipv4_address: 192.168.1.83
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        
# networks:
#     default:
#         external:
#             name: macvlan
