name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Init
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.NAS_SSH_HOST}}
          username: ${{ secrets.NAS_SSH_USERNAME }}
          password: ${{ secrets.NAS_SSH_PASSWORD }}
          script: |
            cd www/music-engine
            git pull
            sudo docker-compose up -d --build --force-recreate